{% set name = "opentelemetry-instrumentation-asgi" %}
{% set version = "0.28b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-asgi-{{ version }}.tar.gz
  sha256: 47e88f555899798e55a87ba17e84d80cc3ec115116354d4cf1172bccb9fca9ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b0
    - opentelemetry-semantic-conventions ==0.28b0
    - opentelemetry-util-http ==0.28b0
    - python >=3.6
    - asgiref ~=3.0
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-test-utils ==0.28b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  summary: ASGI instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
