{% set name = "opentelemetry-instrumentation-asgi" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_asgi-{{ version }}.tar.gz
  sha256: 2509d6fe9fd829399ce3536e3a00426c7e3aa359fc1ed9ceee1628b56da40e7a

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - asgiref >=3.0,<4
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation ==0.59b0
    - opentelemetry-semantic-conventions ==0.59b0
    - opentelemetry-util-http ==0.59b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation.asgi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  doc_url: https://opentelemetry.io/docs/
  summary: ASGI instrumentation for OpenTelemetry
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - rxm7706
